// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";
// Load the global monorepo .env (app/web/omnipost-web/.env), resolved from this
// file's location so it works regardless of the current working directory.
const here = dirname(fileURLToPath(import.meta.url));
config({ path: resolve(here, "../../.env") });
export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        url: env("DATABASE_URL"),
    },
});
